variables:
    SUPER_LINTER_VERSION: v3.13.1
  
trigger: none

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    docker pull github/super-linter:$(SUPER_LINTER_VERSION)
    docker run -e RUN_LOCAL=true -e VALIDATE_MD=true -e VALIDATE_YAML=true \
    -e VALIDATE_BASH=true -e VALIDATE_ENV=true -e VALIDATE_JAVA=true \
    -v $(System.DefaultWorkingDirectory):/tmp/lint github/super-linter:$(SUPER_LINTER_VERSION)
  displayName: 'Code Scan using GitHub Super-Linter'
