variables:
    SUPER_LINTER_VERSION: v3.13.1
  
trigger: none

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    mkdir -p .github/linters
    curl -o .github/linters/sun_checks.xml https://raw.githubusercontent.com/wso2/code-quality-tools/cloud/checkstyle/checkstyle.xml
  displayName: 'Download checkstyle.xml'
- script: |
    docker pull github/super-linter:$(SUPER_LINTER_VERSION)
    docker run -e RUN_LOCAL=true -e VALIDATE_MD=true -e VALIDATE_YAML=true \
    -e VALIDATE_BASH=true -e VALIDATE_ENV=true -e VALIDATE_JAVA=true \
    -v $(System.DefaultWorkingDirectory):/tmp/lint github/super-linter:$(SUPER_LINTER_VERSION)
  displayName: 'Code Scan using GitHub Super-Linter'
